CREATE TABLE "ASU_USER"."ACCOUNTS" (
	"ACC_ID" NUMBER(10) NOT NULL,
    "ACC_LOGIN" VARCHAR2(20) NOT NULL, 
	"ACC_PASSWORD" VARCHAR2(20) NOT NULL, 
	"ACC_ROLE" NUMBER(10) NOT NULL, 
	"ACC_INFO" NUMBER(10) NOT NULL
) TABLESPACE "USERS";