SPOOL create_constraints.lst;
PROMPT Автор: Щелбанин Александр ВЛадимирович;
PROMPT Группа: ИУ4-83;
PROMPT Создание ограничений БД для АСУ ТП изготовления RR-701-R-T;


PROMPT Создание ограничения C_ACC_LOGIN;
ALTER TABLE ASU_USER.ACCOUNTS
  DROP CONSTRAINT C_ACC_LOGIN;
ALTER TABLE ASU_USER.ACCOUNTS ADD (
  CONSTRAINT C_ACC_LOGIN UNIQUE(ACC_LOGIN)
  );
PROMPT Создание ограничения успешно завершено;

PROMPT Создание ограничения C_USER_PHONE;
ALTER TABLE ASU_USER.USERS 
	DROP CONSTRAINT C_USER_PHONE;
ALTER TABLE ASU_USER.USERS ADD (
  CONSTRAINT C_USER_PHONE CHECK (
    USER_PHONE LIKE '8-___-___-__-__'
  )
);
PROMPT Создание ограничения успешно завершено;

PROMPT Создание ограничения C_DOC_URL;
ALTER TABLE ASU_USER.DOCUMENTS
  DROP CONSTRAINT C_DOC_URL;
ALTER TABLE ASU_USER.DOCUMENTS ADD (
  CONSTRAINT C_DOC_URL CHECK (DOC_URL LIKE 'http://%.%')
);
PROMPT Создание ограничения успешно завершено;

PROMPT Создание ограничений для таблицы DATES;
ALTER TABLE ASU_USER.DATES
  DROP CONSTRAINT DATE_START_SPEC;
ALTER TABLE ASU_USER.DATES ADD (
  CONSTRAINT С_DATE_START_SPEC CHECK(DATE_START_SPEC LIKE '__.__.____'));

ALTER TABLE ASU_USER.DATES
  DROP CONSTRAINT DATE_END_SPEC;
ALTER TABLE ASU_USER.DATES ADD (
  CONSTRAINT С_DATE_END_SPEC CHECK(DATE_END_SPEC LIKE '__.__.____'));

ALTER TABLE ASU_USER.DATES
  DROP CONSTRAINT DATE_START_FACT;
ALTER TABLE ASU_USER.DATES ADD (
  CONSTRAINT С_DATE_START_FACT CHECK(DATE_START_FACT LIKE '__.__.____'));

ALTER TABLE ASU_USER.DATES
  DROP CONSTRAINT DATE_END_FACT;
ALTER TABLE ASU_USER.DATES ADD (
  CONSTRAINT С_DATE_END_FACT CHECK(DATE_END_FACT LIKE '__.__.____'));
PROMPT Создание ограничений успешно завершено;


PROMPT Работа скрипта успешно завершена;
SPOOL OFF;
