ALTER TABLE ASU_USER.PREPARATION
  DROP CONSTRAINT C_PREP_UNBOXING;
ALTER TABLE ASU_USER.PREPARATION ADD (
  CONSTRAINT C_PREP_UNBOXING CHECK (
    PREP_UNBOXING IN (
      SELECT OPER_ID
        FROM OPERATION_INFO
        WHERE OPER_TYPE = (
          SELECT OTYP_ID
            FROM OPERATION_TYPE
            WHERE OTYP_NAME = 'Подготовка комплектующих'
        )
    )
  )
);

ALTER TABLE ASU_USER.PREPARATION
  DROP CONSTRAINT C_PREP_CONTROL;
ALTER TABLE ASU_USER.PREPARATION ADD (
  CONSTRAINT C_PREP_CONTROL CHECK (
    PREP_CONTROL IN (
      SELECT OPER_ID
      FROM OPERATION_INFO
      WHERE OPER_TYPE = (
        SELECT OTYP_ID
        FROM OPERATION_TYPE
        WHERE OTYP_NAME = 'Подготовка комплектующих'
      )
    )
  )
);